name: CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
        gemfile:
          - rails_5_2
          - rails_6
          - rails_6_1
          - rails_7
          - rails_7_1
        exclude:
          - ruby: '3.0'
            gemfile: 'rails_5_2'
          - ruby: '3.1'
            gemfile: 'rails_5_2'
          - ruby: '3.2'
            gemfile: 'rails_5_2'
          - ruby: '3.2'
            gemfile: 'rails_6'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Ruby ${{ matrix.ruby-version }} with Rails ${{ matrix.gemfile }}
        run: |
          GEMFILE=${{ matrix.gemfile }}
          RAILS_VERSION="${GEMFILE//_/-}"
          echo $RAILS_VERSION
          bundle exec appraisal $RAILS_VERSION rake

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests pass"
          else
            echo "Some tests failed"
            false
          fi
